import Head from 'next/head';
import {BookSlider, HeadSlider,Banner} from "../components";
import {useEffect, useState} from "react";
import {useService} from "./../hooks";
export default function Home() {
    const service=useService();
    const [culturalSlider,setCulturalSlider]=useState([]);
    const [artisticSlider,setArtisticSlider]=useState([]);
    const [humorousSlider,setHumorousSlider]=useState([]);
    useEffect(()=>{
        service("get","books",{page:1,pagination:true,"categories.title":"فرهنگی","_order[createdAt]":"asc"}).then(data=>{
            let cash=data["hydra:member"].map(item=>({name:item.name,image:`http://sanab.erbp.ir/public/files/${item.image.url}`,link:`/books/${item.id}`}));
            setCulturalSlider(cash);
        });
        service("get","books",{page:1,pagination:true,"categories.title":"هنری","_order[createdAt]":"asc"}).then(data=>{
            let cash=data["hydra:member"].map(item=>({name:item.name,image:`http://sanab.erbp.ir/public/files/${item.image.url}`,link:`/books/${item.id}`}));
            setArtisticSlider(cash);
        });
        service("get","books",{page:1,pagination:true,"categories.title":"طنز","_order[createdAt]":"asc"}).then(data=>{
            let cash=data["hydra:member"].map(item=>({name:item.name,image:`http://sanab.erbp.ir/public/files/${item.image.url}`,link:`/books/${item.id}`}));
            setHumorousSlider(cash);
        })
    },[]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <HeadSlider items={[
        {
            name:"هر گوشی هوشمند یک کتابخانه",
            image:"/assets/temp/Untitled-1.jpg",
            caption:<div dir="rtl"><h4>همین حالا برنامه سناب  را  برای گوشی خود دریافت کنید</h4><button className="btn">دریافت برنامه</button></div>
        },
        {
            name:"کمپین هر هفته یک کتاب",
            image:"/assets/temp/Untitled-2.jpg",
            caption:<div><button className="btn white">شرکت در کمپین</button></div>
        },
        ]}/>
      <BookSlider
          title={"تازه های فرهنگی"}
          items={culturalSlider}
      />
      <Banner link="/" image="http://sanab.erbp.ir/public/files//60fd3424556d8456406714.jpg"/>
      <BookSlider
          title={"تازه های هنری"}
            items={artisticSlider}
      />
      <Banner link="/books/12" image="http://sanab.erbp.ir/public/files//60fd3424556d8456406714.jpg"/>
          <BookSlider
              title={"تازه های طنز"}
                items={humorousSlider}
          />
      </section>
    </div>
  )
}
