import Head from 'next/head';
import {HeadSlider} from "../components";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <HeadSlider items={[
        {
            name:"هر گوشی هوشمند یک کتابخانه",
            image:"/assets/temp/Untitled-1.jpg",
            caption:<div dir="rtl"><h4>همین حالا برنامه سناب  را  برای گوشی خود دریافت کنید</h4><button className="btn">دریافت برنامه</button></div>
        },
        {
            name:"کمپین هر هفته یک کتاب",
            image:"/assets/temp/Untitled-2.jpg",
            caption:<div><button className="btn white">شرکت در کمپین</button></div>
        },
        ]}/>
      </section>
    </div>
  )
}
