import Head from 'next/head';
import {HeadSlider} from "../components";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <HeadSlider items={[
          {name:"مثال",link:"/",author:"پیمان احمدیان",publisher:"احمدیان",image:"http://sanab.erbp.ir/public/files//60fd2fcb544e1646123945.jpg"},
          {name:"مثال بعدی",link:"/",author:"نعیم احمدیان",publisher:"احمدیان"},
          {name:"مثال بعدی",link:"/",author:"نعیم احمدیان",publisher:"احمدیان"}
        ]}/>
      </section>
    </div>
  )
}
